exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

#github:
#  private: false
#  source:
#    branch: "main"
#    path: "/"
#  repository_url: "https://github.com/keepandroidopen/keepandroidopen.github.io"
  
#title: Jekyll Theme Primer
#description: Primer is a Jekyll theme for GitHub Pages

